### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kgashok** [loganayaki2306/addressbook#1]
@loganayaki2306 @ramyaramkumar Good effort so far! 

However, what more is planned to be added to the project? Provide some action items (and deadlines) for what will be accomplished

1 Before the Academic Viva (probably ~ Apr 9, 10, 2016)
2 After the Academic Viva (probably until June 1 2016)

**Comment by loganayaki2306** [comment]
Sir,
1. We have planned to complete E-campus and GPS module  integration within the academic viva.
2. After completing these modules we will covert the desktop application into android application.
Thanks and Regards.

**Comment by kgashok** [comment]
What exactly is your plan with E-campus? What will it do? How much hours of work do you estimate? 
What exactly is your plan with GPS module? What will it do? How much hours of work do you estimate?

**Comment by ramyaramkumar** [comment]
1.In E-campus module the alumini's of our college can get their batch mates contact informations and can send group message regarding emergency message such as job fair, college events and blood group notification.
2.In GPS module we will receive the location information about our friends who are available near by.

**Comment by kgashok** [comment]
Your plans have been split up into individual issues and added. This "roadmap" comment can now be closed.
